### ISSUE TITLE
Querying an invalid custom metrics API path results in a panic

### ISSUE THREAD

**Issue by dgrisonnet** [kubernetes-sigs/custom-metrics-apiserver#78]
Querying an incorrect custom metrics API path may result in a panic from custom-metrics-apiserver. Usually, when the query is malformed the adapter would respond HTTP 404; however, for the following query, it responds HTTP 503 and a panic can be found in the adapter logs. This panic seems to occur whenever only the first half of the query path is valid.

This error was reported by a couple of prometheus-adapter users who were misled by the query output and the logs:
- https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/315
- https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/338

This issue doesn't seem to have a direct impact on the adapter but the error is quite misleading to the end-users.

### Query

```sh
$ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/*/metric_name"
Error from server (ServiceUnavailable): the server is currently unable to handle the request
```
> Note: the valid query would be: kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/*/**metrics**/metric_name"

### Logs

```
I1119 10:55:58.662995       1 httplog.go:89] "HTTP" verb="GET" URI="/apis/custom.metrics.k8s.io/v1beta1/namespaces/%2A/metric_name" latency="5.664053ms"       userAgent="kubectl/v1.18.1 (linux/amd64) kubernetes/7879fc1" srcIP="192.168.122.188:49898" resp=0
E1119 10:55:58.663068       1 runtime.go:76] Observed a panic: runtime error: slice bounds out of range [2:1]
goroutine 891 [running]:
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc0007d0a20)
        /home/damien/github/dgrisonnet/custom-metrics-apiserver/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x113
panic(0x1b9ee40, 0xc0007fc500)
        /usr/lib/go/src/runtime/panic.go:969 +0x1b9
github.com/kubernetes-sigs/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers.getRequestOptions(0xc00094b900, 0x1f632e0, 0xc0007651c0, 0x1f53b00,       0xc0004ac9c0, 0x1f1da80, 0xc000764900, 0x0, 0x0, 0x0, ...)
        /home/damien/github/dgrisonnet/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers/get.go:160 +0x63c
github.com/kubernetes-sigs/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers.ListResourceWithOptions.func1(0x1f51ac0, 0xc000378d30, 0xc00094b900)
        /home/damien/github/dgrisonnet/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers/get.go:111 +0x4c7
github.com/kubernetes-sigs/custom-metrics-apiserver/pkg/apiserver/installer.restfulListResourceWithOptions.func1(0xc00087dd40, 0xc0004c0690)
        /home/damien/github/dgrisonnet/custom-metrics-apiserver/pkg/apiserver/installer/installer.go:297 +0xed
k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc00087dd40, 0xc0004c0690)
        /home/damien/github/dgrisonnet/custom-metrics-apiserver/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:384 +0x282
github.com/emicklei/go-restful.(*Container).dispatch(0xc000352ab0, 0x7f09a9ea63c0, 0xc000378d28, 0xc00094b900)
        /home/damien/github/dgrisonnet/custom-metrics-apiserver/vendor/github.com/emicklei/go-restful/container.go:294 +0x65a
github.com/emicklei/go-restful.(*Container).Dispatch(...)
        /home/damien/github/dgrisonnet/custom-metrics-apiserver/vendor/github.com/emicklei/go-restful/container.go:204
k8s.io/apiserver/pkg/server.director.ServeHTTP(0x1cc26de, 0x16, 0xc000352ab0, 0xc0002f2a10, 0x7f09a9ea63c0, 0xc000378d28, 0xc00094b900)
        /home/damien/github/dgrisonnet/custom-metrics-apiserver/vendor/k8s.io/apiserver/pkg/server/handler.go:146 +0x539
k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f09a9ea63c0, 0xc000378d28, 0xc00094b900)
        /home/damien/github/dgrisonnet/custom-metrics-apiserver/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x563
net/http.HandlerFunc.ServeHTTP(0xc0004e3700, 0x7f09a9ea63c0, 0xc000378d28, 0xc00094b900)
        /usr/lib/go/src/net/http/server.go:2042 +0x44
k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func2(0x7f09a9ea63c0, 0xc000378d28, 0xc00094b900)
        /home/damien/github/dgrisonnet/custom-metrics-apiserver/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:175 +0x4cf
net/http.HandlerFunc.ServeHTTP(0xc00088a780, 0x7f09a9ea63c0, 0xc000378d28, 0xc00094b900)
        /usr/lib/go/src/net/http/server.go:2042 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f09a9ea63c0, 0xc000378d28, 0xc00094b900)
        /home/damien/github/dgrisonnet/custom-metrics-apiserver/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x231d
net/http.HandlerFunc.ServeHTTP(0xc0004e3740, 0x7f09a9ea63c0, 0xc000378d28, 0xc00094b900)
        /usr/lib/go/src/net/http/server.go:2042 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f09a9ea63c0, 0xc000378d28, 0xc00094b800)
        /home/damien/github/dgrisonnet/custom-metrics-apiserver/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:70 +0x672
net/http.HandlerFunc.ServeHTTP(0xc000255c20, 0x7f09a9ea63c0, 0xc000378d28, 0xc00094b800)
        /usr/lib/go/src/net/http/server.go:2042 +0x44
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc0007d0a20, 0xc0004c9680, 0x1f57140, 0xc000378d28, 0xc00094b800)
        /home/damien/github/dgrisonnet/custom-metrics-apiserver/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:113 +0xb8
created by k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /home/damien/github/dgrisonnet/custom-metrics-apiserver/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x1cc
```

**Comment by dgrisonnet** [comment]
/remove-lifecycle stale

This bug is still valid.

**Comment by YouHang** [comment]
A validation can be added to check the length of the `requestInfo.Parts`. https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/85
